//>>built
require({cache:{"xstyle/css":function(){define(["require"],function(l){function k(h,d,c){var a=document.documentElement;h=a.insertBefore(document.createElement(h),a.firstChild);h.id=d;d=(h.currentStyle||getComputedStyle(h,null))[c];a.removeChild(h);return d}return{load:function(h,d,c,a){function g(){var b=k("x-parse",null,"content");b&&"none"!=b?d([eval(b)],c):c()}var e=d.toUrl(h),f=d.cache["url:"+e];if(f)return f.xCss&&(f=f.cssText),l(["./util/createStyleSheet"],function(b){b(f)}),g();if("none"==
k("div",h.replace(/\//g,"-").replace(/\..*/,"")+"-loaded","display"))return g();l(["./load-css"],function(b){b(e,g)})}}})},"dbootstrap/icon_support":function(){define("require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-class dijit/_TemplatedMixin".split(" "),function(l,k,h,d,c,a,g){var e=function(b){var e=["IMG","INPUT"],w="dijitIcon dijitTabStripIcon dijitMenuExpand dijitCalendarIncrementControl dijitArrowButtonInner dijitTreeExpando dijitArrowNode".split(" "),
m=["class","data-dojo-attach-point"],g=b;h.isArray(g)||(g=b.all||b.getElementsByTagName("*"));for(var p=h.isArray(b)?0:-1;0>p||g[p];p++){var f=-1==p?b:g[p];if(-1!==d.indexOf(e,f.tagName))for(var k=0,l=w.length;k<l;k++)if(a.contains(f,w[k])){var u={};d.forEach(m,function(b){var m=f.getAttribute(b);m&&(u[b]=m)});c.create("span",u,f,"replace");break}}};if(void 0===g.prototype._attachTemplateNodes)l(["dijit/_AttachMixin"],function(b){var a=b.prototype._attachTemplateNodes;b.prototype._attachTemplateNodes=
function(b){e(b);return a.call(this,b)}});else{var f=g.prototype._attachTemplateNodes;g.prototype._attachTemplateNodes=function(b,a){e(b);return f.call(this,b,a)}}return g})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),function(l,k,h,d,c,a,g,e){var f=k("dijit._TemplatedMixin",e,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(b){var a=
this.declaredClass,c=this;return g.substitute(b,this,function(b,e){"!"==e.charAt(0)&&(b=d.getObject(e.substr(1),!1,c));if("undefined"==typeof b)throw Error(a+" template:"+e);return null==b?"":"!"==e.charAt(0)?b:b.toString().replace(/"/g,"\x26quot;")},this)},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=l(this.templatePath,{sanitize:!0}));var b=f.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),a;if(d.isString(b)){if(a=h.toDom(this._stringRepl(b),
this.ownerDocument),1!=a.nodeType)throw Error("Invalid template: "+b);}else a=b.cloneNode(!0);this.domNode=a}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);this._rendered=!0},_fillContent:function(b){var a=this.containerNode;if(b&&a)for(;b.hasChildNodes();)a.appendChild(b.firstChild)}});f._templateCache={};f.getCachedTemplate=function(b,a,c){var m=f._templateCache,e=b,d=m[e];if(d){try{if(!d.ownerDocument||d.ownerDocument==(c||document))return d}catch(k){}h.destroy(d)}b=
g.trim(b);if(a||b.match(/\$\{([^\}]+)\}/g))return m[e]=b;a=h.toDom(b,c);if(1!=a.nodeType)throw Error("Invalid template: "+b);return m[e]=a};a("ie")&&c(window,"unload",function(){var b=f._templateCache,a;for(a in b){var c=b[a];"object"==typeof c&&h.destroy(c);delete b[a]}});return f})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(l){return l.cache})},"dojo/text":function(){define(["./_base/kernel","require","./has","./request"],function(l,k,h,d){var c;c=function(b,a,c){d(b,{sync:!!a}).then(c)};
var a={},g=function(b){if(b){b=b.replace(/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,"");var a=b.match(/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im);a&&(b=a[1])}else b="";return b},e={},f={};l.cache=function(b,e,d){var m;"string"==typeof b?/\//.test(b)?(m=b,d=e):m=k.toUrl(b.replace(/\./g,"/")+(e?"/"+e:"")):(m=b+"",d=e);b=void 0!=d&&"string"!=typeof d?d.value:d;d=d&&d.sanitize;if("string"==typeof b)return a[m]=b,d?g(b):b;if(null===b)return delete a[m],null;m in a||c(m,!0,function(b){a[m]=
b});return d?g(a[m]):a[m]};return{dynamic:!0,normalize:function(b,a){var c=b.split("!"),m=c[0];return(/^\./.test(m)?a(m):m)+(c[1]?"!"+c[1]:"")},load:function(b,d,h){b=b.split("!");var m=1<b.length,k=b[0],p=d.toUrl(b[0]);b="url:"+p;var l=e,x=function(b){h(m?g(b):b)};k in a?l=a[k]:d.cache&&b in d.cache?l=d.cache[b]:p in a&&(l=a[p]);if(l===e)if(f[p])f[p].push(x);else{var r=f[p]=[x];c(p,!d.async,function(b){a[k]=a[p]=b;for(var m=0;m<r.length;)r[m++](b);delete f[p]})}else x(l)}}})},"dojo/request":function(){define(["./request/default!"],
function(l){return l})},"dojo/request/default":function(){define(["exports","require","../has"],function(l,k,h){var d=h("config-requestProvider");d||(d="./xhr");l.getPlatformDefaultId=function(){return"./xhr"};l.load=function(c,a,g,e){k(["platform"==c?"./xhr":d],function(a){g(a)})}})},"dojo/string":function(){define(["./_base/kernel","./_base/lang"],function(l,k){var h={};k.setObject("dojo.string",h);h.rep=function(d,c){if(0>=c||!d)return"";for(var a=[];;){c&1&&a.push(d);if(!(c>>=1))break;d+=d}return a.join("")};
h.pad=function(d,c,a,g){a||(a="0");d=String(d);c=h.rep(a,Math.ceil((c-d.length)/a.length));return g?d+c:c+d};h.substitute=function(d,c,a,g){g=g||l.global;a=a?k.hitch(g,a):function(a){return a};return d.replace(/\$\{([^\s\:\}]+)(?:\:([^\s\:\}]+))?\}/g,function(d,f,b){d=k.getObject(f,!1,c);b&&(d=k.getObject(b,!1,g).call(g,d,f));return a(d,f).toString()})};h.trim=String.prototype.trim?k.trim:function(d){d=d.replace(/^\s+/,"");for(var c=d.length-1;0<=c;c--)if(/\S/.test(d.charAt(c))){d=d.substring(0,c+
1);break}return d};return h})},"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),function(l,k,h,d,c,a,g,e,f){var b=c.delegate(e,{mouseenter:a.enter,mouseleave:a.leave,keypress:h._keypress}),q;h=d("dijit._AttachMixin",null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);
this._beforeFillContent()},_beforeFillContent:function(){},_attachTemplateNodes:function(b){for(var a=b;;)if(1==a.nodeType&&(this._processTemplateNode(a,function(b,a){return b.getAttribute(a)},this._attach)||this.searchContainerNode)&&a.firstChild)a=a.firstChild;else{if(a==b)break;for(;!a.nextSibling;)if(a=a.parentNode,a==b)return;a=a.nextSibling}},_processTemplateNode:function(b,a,d){var e=!0,g=this.attachScope||this,f=a(b,"dojoAttachPoint")||a(b,"data-dojo-attach-point");if(f)for(var k=f.split(/\s*,\s*/);f=
k.shift();)c.isArray(g[f])?g[f].push(b):g[f]=b,e="containerNode"!=f,this._attachPoints.push(f);if(a=a(b,"dojoAttachEvent")||a(b,"data-dojo-attach-event")){f=a.split(/\s*,\s*/);for(k=c.trim;a=f.shift();)if(a){var h=null;-1!=a.indexOf(":")?(h=a.split(":"),a=k(h[0]),h=k(h[1])):a=k(a);h||(h=a);this._attachEvents.push(d(b,a,c.hitch(g,h)))}}return e},_attach:function(a,c,d){c=c.replace(/^on/,"").toLowerCase();c="dijitclick"==c?q||(q=l("./a11yclick")):b[c]||c;return g(a,c,d)},_detachTemplateNodes:function(){var a=
this.attachScope||this;k.forEach(this._attachPoints,function(b){delete a[b]});this._attachPoints=[];k.forEach(this._attachEvents,function(a){a.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();this.inherited(arguments)}});c.extend(f,{dojoAttachEvent:"",dojoAttachPoint:""});return h})},"dojo/touch":function(){define("./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(l,k,h,d,c,a,g,e,f,b){function q(b,
n,c){return A&&c?function(b,n){return a(b,c,n)}:z?function(c,d){var e=a(c,n,d),D=a(c,b,function(a){(!y||(new Date).getTime()>y+1E3)&&d.call(this,a)});return{remove:function(){e.remove();D.remove()}}}:function(n,c){return a(n,b,c)}}function w(a){do if(a.dojoClick)return a.dojoClick;while(a=a.parentNode)}function m(n,c,e){if(r=!n.target.disabled&&w(n.target))u=n.target,s=n.touches?n.touches[0].pageX:n.clientX,t=n.touches?n.touches[0].pageY:n.clientY,C=("object"==typeof r?r.x:"number"==typeof r?r:0)||
4,v=("object"==typeof r?r.y:"number"==typeof r?r:0)||4,x||(x=!0,b.doc.addEventListener(c,function(a){r=r&&a.target==u&&Math.abs((a.touches?a.touches[0].pageX:a.clientX)-s)<=C&&Math.abs((a.touches?a.touches[0].pageY:a.clientY)-t)<=v},!0),b.doc.addEventListener(e,function(b){if(r){B=(new Date).getTime();var n=b.target;"LABEL"===n.tagName&&(n=h.byId(n.getAttribute("for"))||n);setTimeout(function(){a.emit(n,"click",{bubbles:!0,cancelable:!0,_dojo_click:!0})})}},!0),n=function(a){b.doc.addEventListener(a,
function(b){!b._dojo_click&&((new Date).getTime()<=B+1E3&&!("INPUT"==b.target.tagName&&d.contains(b.target,"dijitOffScreen")))&&(b.stopPropagation(),b.stopImmediatePropagation&&b.stopImmediatePropagation(),"click"==a&&(("INPUT"!=b.target.tagName||"radio"==b.target.type||"checkbox"==b.target.type)&&"TEXTAREA"!=b.target.tagName&&"AUDIO"!=b.target.tagName&&"VIDEO"!=b.target.tagName)&&b.preventDefault())},!0)},n("click"),n("mousedown"),n("mouseup"))}var z=g("touch"),p=5>g("ios"),A=navigator.msPointerEnabled,
x,r,u,s,t,C,v,B,y,n;z&&(A?f(function(){b.doc.addEventListener("MSPointerDown",function(a){m(a,"MSPointerMove","MSPointerUp")},!0)}):f(function(){function d(a){var b=c.delegate(a,{bubbles:!0});6<=g("ios")&&(b.touches=a.touches,b.altKey=a.altKey,b.changedTouches=a.changedTouches,b.ctrlKey=a.ctrlKey,b.metaKey=a.metaKey,b.shiftKey=a.shiftKey,b.targetTouches=a.targetTouches);return b}n=b.body();b.doc.addEventListener("touchstart",function(b){y=(new Date).getTime();var c=n;n=b.target;a.emit(c,"dojotouchout",
{relatedTarget:n,bubbles:!0});a.emit(n,"dojotouchover",{relatedTarget:c,bubbles:!0});m(b,"touchmove","touchend")},!0);a(b.doc,"touchmove",function(c){y=(new Date).getTime();var e=b.doc.elementFromPoint(c.pageX-(p?0:b.global.pageXOffset),c.pageY-(p?0:b.global.pageYOffset));e&&(n!==e&&(a.emit(n,"dojotouchout",{relatedTarget:e,bubbles:!0}),a.emit(e,"dojotouchover",{relatedTarget:n,bubbles:!0}),n=e),a.emit(e,"dojotouchmove",d(c)))});a(b.doc,"touchend",function(n){y=(new Date).getTime();var c=b.doc.elementFromPoint(n.pageX-
(p?0:b.global.pageXOffset),n.pageY-(p?0:b.global.pageYOffset))||b.body();a.emit(c,"dojotouchend",d(n))})}));k={press:q("mousedown","touchstart","MSPointerDown"),move:q("mousemove","dojotouchmove","MSPointerMove"),release:q("mouseup","dojotouchend","MSPointerUp"),cancel:q(e.leave,"touchcancel",z?"MSPointerCancel":null),over:q("mouseover","dojotouchover","MSPointerOver"),out:q("mouseout","dojotouchout","MSPointerOut"),enter:e._eventHandler(q("mouseover","dojotouchover","MSPointerOver")),leave:e._eventHandler(q("mouseout",
"dojotouchout","MSPointerOut"))};return l.touch=k})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),function(l,k,h,d,c,a,g,e,f,b,q,w,m,z,p,A,x,r,u,s,t,C,
v){function B(a){return function(b){e[b?"set":"remove"](this.domNode,a,b);this._set(a,b)}}m.add("dijit-legacy-requires",!z.isAsync);m.add("dojo-bidi",!1);m("dijit-legacy-requires")&&x(0,function(){l(["dijit/_base/manager"])});var y={};d=a("dijit._WidgetBase",[r,t],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:B("lang"),dir:"",_setDirAttr:B("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,
_setOwnerDocumentAttr:function(a){this._set("ownerDocument",a)},attributeMap:{},_blankGif:d.blankGif||l.toUrl("dojo/resources/blank.gif"),_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var b=a.prototype,c=a._setterAttrs=[],a=a._onMap={},d;for(d in b.attributeMap)c.push(d);for(d in b)/^on/.test(d)&&(a[d.substring(2).toLowerCase()]=d),/^_set[A-Z](.*)Attr$/.test(d)&&(d=d.charAt(4).toLowerCase()+d.substr(5,d.length-9),(!b.attributeMap||!(d in b.attributeMap))&&c.push(d))}},postscript:function(a,
b){this.create(a,b)},create:function(a,b){this._introspect();this.srcNodeRef=g.byId(b);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);a&&(this.params=a,p.mixin(this,a));this.postMixInProperties();this.id||(this.id=v.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=
s.body(this.ownerDocument);v.add(this);this.buildRendering();var c;if(this.domNode){this._applyAttributes();var d=this.srcNodeRef;d&&(d.parentNode&&this.domNode!==d)&&(d.parentNode.replaceChild(this.domNode,d),c=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},b;for(b in this.params||{})a[b]=this._get(b);k.forEach(this.constructor._setterAttrs,function(b){if(!(b in a)){var c=this._get(b);c&&this.set(b,
c)}},this);for(b in a)this.set(b,a[b])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(k.map(a,function(a){return a+"Rtl"})));f.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,k.forEach(this.getChildren(),function(a){!a._started&&(!a._destroyed&&p.isFunction(a.startup))&&
(a.startup(),a._started=!0)}))},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function b(c){c.destroyRecursive?c.destroyRecursive(a):c.destroy&&c.destroy(a)}this._beingDestroyed=!0;this.uninitialize();k.forEach(this._connects,p.hitch(this,"disconnect"));k.forEach(this._supportingWidgets,b);this.domNode&&k.forEach(v.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);v.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&
(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?e.remove(this.domNode,"widgetId"):b.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||b.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){k.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;p.isObject(a)?w.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",
a)},_attrToDom:function(a,b,c){c=3<=arguments.length?c:this.attributeMap[a];k.forEach(p.isArray(c)?c:[c],function(c){var d=this[c.node||c||"domNode"];switch(c.type||"attribute"){case "attribute":p.isFunction(b)&&(b=p.hitch(this,b));c=c.attribute?c.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;d.tagName?e.set(d,c,b):d.set(c,b);break;case "innerText":d.innerHTML="";d.appendChild(this.ownerDocument.createTextNode(b));break;case "innerHTML":d.innerHTML=b;break;case "class":f.replace(d,b,this[a])}},
this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?this[b.g]():this._get(a)},set:function(a,b){if("object"===typeof a){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);var d=this[c.s];if(p.isFunction(d))var e=d.apply(this,Array.prototype.slice.call(arguments,1));else{var d=this.focusNode&&!p.isFunction(this.focusNode)?"focusNode":"domNode",g=this[d]&&this[d].tagName,f;if(f=g)if(!(f=y[g])){f=this[d];var m={},h;for(h in f)m[h.toLowerCase()]=!0;f=y[g]=m}h=f;c=a in
this.attributeMap?this.attributeMap[a]:c.s in this?this[c.s]:h&&c.l in h&&"function"!=typeof b||/^aria-|^data-|^role$/.test(a)?d:null;null!=c&&this._attrToDom(a,b,c);this._set(a,b)}return e||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return b[a]={n:a+"Node",s:"_set"+c+"Attr",g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;
this._created&&b!==c&&(this._watchCallbacks&&this._watchCallbacks(a,c,b),this.emit("attrmodified-"+a,{detail:{prevValue:c,newValue:b}}))},_get:function(a){return this[a]},emit:function(a,b,c){b=b||{};void 0===b.bubbles&&(b.bubbles=!0);void 0===b.cancelable&&(b.cancelable=!0);b.detail||(b.detail={});b.detail.widget=this;var d,e=this["on"+a];e&&(d=e.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&A.emit(this.domNode,a.toLowerCase(),b);return d},on:function(a,b){var c=this._onMap(a);return c?
h.after(this,c,b,!0):this.own(A(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;if(!c){var c=b._onMap={},d;for(d in b.prototype)/^on/.test(d)&&(c[d.replace(/^on/,"").toLowerCase()]=d)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?v.findWidgets(this.containerNode):[]},getParent:function(){return v.getEnclosingWidget(this.domNode.parentNode)},
connect:function(a,b,d){return this.own(c.connect(a,b,this,d))[0]},disconnect:function(a){a.remove()},subscribe:function(a,b){return this.own(u.subscribe(a,p.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir:q.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=w.get(this.domNode,"display")},placeAt:function(a,c){var d=!a.tagName&&v.byId(a);d&&d.addChild&&(!c||"number"===typeof c)?d.addChild(this,c):(d=d?d.containerNode&&
!/after|before|replace/.test(c||"")?d.containerNode:d.domNode:g.byId(a,this.ownerDocument),b.place(this.domNode,d,c),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,b){var c=setTimeout(p.hitch(this,function(){c&&(c=null,this._destroyed||p.hitch(this,a)())}),b||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}});m("dojo-bidi")&&d.extend(C);return d})},"dojo/Stateful":function(){define(["./_base/declare","./_base/lang","./_base/array",
"./when"],function(l,k,h,d){return l("dojo.Stateful",null,{_attrPairNames:{},_getAttrNames:function(c){var a=this._attrPairNames;return a[c]?a[c]:a[c]={s:"_"+c+"Setter",g:"_"+c+"Getter"}},postscript:function(c){c&&this.set(c)},_get:function(c,a){return"function"===typeof this[a.g]?this[a.g]():this[c]},get:function(c){return this._get(c,this._getAttrNames(c))},set:function(c,a){if("object"===typeof c){for(var g in c)c.hasOwnProperty(g)&&"_watchCallbacks"!=g&&this.set(g,c[g]);return this}g=this._getAttrNames(c);
var e=this._get(c,g);g=this[g.s];var f;"function"===typeof g?f=g.apply(this,Array.prototype.slice.call(arguments,1)):this[c]=a;if(this._watchCallbacks){var b=this;d(f,function(){b._watchCallbacks(c,e,a)})}return this},_changeAttrValue:function(c,a){var d=this.get(c);this[c]=a;this._watchCallbacks&&this._watchCallbacks(c,d,a);return this},watch:function(c,a){var d=this._watchCallbacks;if(!d)var e=this,d=this._watchCallbacks=function(a,b,c,f){var h=function(d){if(d){d=d.slice();for(var f=0,g=d.length;f<
g;f++)d[f].call(e,a,b,c)}};h(d["_"+a]);f||h(d["*"])};!a&&"function"===typeof c?(a=c,c="*"):c="_"+c;var f=d[c];"object"!==typeof f&&(f=d[c]=[]);f.push(a);var b={};b.unwatch=b.remove=function(){var b=h.indexOf(f,a);-1<b&&f.splice(b,1)};return b}})})},"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(l,k,h){return h("dijit.Destroyable",null,{destroy:function(d){this._destroyed=!0},own:function(){l.forEach(arguments,function(d){var c="destroyRecursive"in
d?"destroyRecursive":"destroy"in d?"destroy":"remove",a=k.before(this,"destroy",function(a){d[c](a)}),g=k.after(d,c,function(){a.remove();g.remove()},!0)},this);return arguments}})})},"dijit/registry":function(){define(["dojo/_base/array","dojo/sniff","dojo/_base/window","./main"],function(l,k,h,d){var c={},a={},g={length:0,add:function(c){if(a[c.id])throw Error("Tried to register widget with id\x3d\x3d"+c.id+" but that id is already registered");a[c.id]=c;this.length++},remove:function(c){a[c]&&
(delete a[c],this.length--)},byId:function(c){return"string"==typeof c?a[c]:c},byNode:function(c){return a[c.getAttribute("widgetId")]},toArray:function(){var c=[],d;for(d in a)c.push(a[d]);return c},getUniqueId:function(e){var f;do f=e+"_"+(e in c?++c[e]:c[e]=0);while(a[f]);return"dijit"==d._scopeName?f:d._scopeName+"_"+f},findWidgets:function(c,d){function b(c){for(c=c.firstChild;c;c=c.nextSibling)if(1==c.nodeType){var e=c.getAttribute("widgetId");e?(e=a[e])&&g.push(e):c!==d&&b(c)}}var g=[];b(c);
return g},_destroyAll:function(){d._curFocus=null;d._prevFocus=null;d._activeStack=[];l.forEach(g.findWidgets(h.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(c){for(;c;){var d=1==c.nodeType&&c.getAttribute("widgetId");if(d)return a[d];c=c.parentNode}return null},_hash:a};return d.registry=g})},"dijit/main":function(){define(["dojo/_base/kernel"],function(l){return l.dijit})},"xstyle/load-css":function(){define([],
function(){function l(b,c){var d=b[a]("link");d.rel="stylesheet";d.type="text/css";c&&(d.href=c);return d}function k(a){a=a.split("!");for(var b,c=1;b=a[c++];)b=b.split("\x3d",2),a[b[0]]=2==b.length?b[1]:!0;return a}function h(a){if(b["dom-create-style-element"])return c=document.createElement("style"),c.setAttribute("type","text/css"),c.appendChild(document.createTextNode(a)),q.insertBefore(c,q.firstChild),c;var c=document.createStyleSheet();c.cssText=a;return c.owningElement}var d="onreadystatechange",
c="onload",a="createElement",g=!1,e=document,f="undefined"==typeof _css_cache?{}:_css_cache,b={"event-link-onload":null===document.createElement("link").onload&&!navigator.userAgent.match(/AppleWebKit/),"dom-create-style-element":!document.createStyleSheet},q=e.head||(e.head=e.getElementsByTagName("head")[0]);if(!b["bundled-css"])var w=function(a,f){function e(a){if(a=a.sheet||a.styleSheet)for(var b=document.styleSheets,c=b.length;0<c;c--)if(b[c-1]==a)return!0}function h(a,b){e(a.link)?(k(a),b()):
g||setTimeout(function(){h(a,b)},a.wait)}function k(a){a=a.link;a[d]=a[c]=null}function l(){q||(q=!0,f())}require.onError&&(require.onError=function(a){return function(){g=!0;a.apply(this,arguments)}}(require.onError));var q;(function(a,f){var e=a.link;e[d]=e[c]=function(){if(!e.readyState||"complete"==e.readyState)b["event-link-onload"]=!0,k(a),f()}})(a,l);b["event-link-onload"]||h(a,l)};return function(a,b,c){for(var d=a.split(","),g=d.length,r=function(){0==--g&&b(t.sheet||t.styleSheet)},u=0;u<
d.length;u++){a=d[u];var s=f[a];if(s)return t=h(s),r();a=k(a);var s=a.shift(),s=s.lastIndexOf(".")<=s.lastIndexOf("/")?s+".css":s,t=l(e);a="nowait"in a?"false"!=a.nowait:!(!c||!c.cssDeferLoad);w({link:t,url:s,wait:c&&c.cssWatchPeriod||25},r);a&&b(t);t.href=s;q.appendChild(t)}}})}}});define("dbootstrap/main",["xstyle/css!./theme/dbootstrap/dbootstrap.css","./icon_support"],function(l){return{TemplatedMixin:l}});
//@ sourceMappingURL=main.js.map